/**
 * SINH TỰ ĐỘNG — ĐỪNG SỬA TAY.
 *
 * Sinh bởi:  npm run eval:model
 * Đo lúc:    2026-09-14
 * Model:     Xenova/quickdraw-mobilevit-small @ fp32
 * Mẫu:       20 hình THẬT mỗi class, lấy từ QuickDraw
 *            full/raw — đúng phân bố của lúc chơi (nét vẽ tay, không phải ảnh
 *            đã rasterize sẵn của Google).
 * Ngưỡng:    top-1 ≥ 0.65
 *
 * ALLOWLIST là SỐ ĐO, không phải danh sách chọn tay. Sửa nó mà không chạy lại
 * `npm run eval:model` nghĩa là đang đoán — và model thì không đoán theo bạn.
 *
 * Muốn thêm từ khoá cho game: chạy lại eval, đừng thêm tay.
 */

/** Ngày đo + tham số, để biết số liệu cũ tới mức nào. */
export const EVAL_META = {
  measuredAt: '2026-09-14',
  model: 'Xenova/quickdraw-mobilevit-small',
  dtype: 'fp32',
  samplesPerClass: 20,
  threshold: 0.65,
} as const;

/** Class mà model nhận đúng ≥ 0.65 ở top-1. Chỉ những class này được làm từ khoá. */
export const ALLOWLIST: readonly string[] = [
  "banana",
  "butterfly",
  "cactus",
  "fireplace",
  "hamburger",
  "helicopter",
  "ice cream",
  "ladder",
  "sink",
  "snail",
  "star",
  "t-shirt",
  "washing machine",
  "airplane",
  "envelope",
  "eyeglasses",
  "flower",
  "floor lamp",
  "hat",
  "jail",
  "mermaid",
  "picture frame",
  "sheep",
  "spoon",
  "swing set",
  "tennis racquet",
  "The Eiffel Tower",
  "The Mona Lisa",
  "umbrella",
  "wine glass",
  "apple",
  "ant",
  "angel",
  "bee",
  "calendar",
  "carrot",
  "circle",
  "church",
  "drill",
  "flashlight",
  "garden",
  "goatee",
  "hammer",
  "hand",
  "kangaroo",
  "lollipop",
  "nose",
  "octopus",
  "palm tree",
  "popsicle",
  "rain",
  "rainbow",
  "sailboat",
  "scorpion",
  "sea turtle",
  "shoe",
  "shorts",
  "snowflake",
  "snowman",
  "square",
  "syringe",
  "television",
  "wine bottle",
  "wristwatch",
  "anvil",
  "alarm clock",
  "basketball",
  "bandage",
  "bat",
  "bulldozer",
  "candle",
  "camel",
  "car",
  "campfire",
  "castle",
  "chandelier",
  "cookie",
  "crab",
  "cruise ship",
  "donut",
  "door",
  "ear",
  "fish",
  "flying saucer",
  "frying pan",
  "giraffe",
  "grass",
  "harp",
  "headphones",
  "hedgehog",
  "hospital",
  "house plant",
  "jacket",
  "key",
  "knee",
  "line",
  "laptop",
  "leaf",
  "lighter",
  "light bulb",
  "lipstick",
  "mountain",
  "mushroom",
  "necklace",
  "octagon",
  "parachute",
  "rabbit",
  "saxophone",
  "see saw",
  "soccer ball",
  "sock",
  "stairs",
  "sun",
  "submarine",
  "table",
  "teapot",
  "teddy-bear",
  "toilet",
  "tractor",
  "tree",
  "waterslide",
  "arm",
  "animal migration",
  "baseball bat",
  "baseball",
  "binoculars",
  "cat",
  "calculator",
  "chair",
  "crocodile",
  "diamond",
  "dresser",
  "drums",
  "elephant",
  "eye",
  "fire hydrant",
  "fork",
  "house",
  "hot air balloon",
  "lightning",
  "megaphone",
  "ocean",
  "owl",
  "pear",
  "peanut",
  "pig",
  "pineapple",
  "rifle",
  "remote control",
  "roller coaster",
  "skateboard",
  "skyscraper",
  "smiley face",
  "stitches",
  "stove",
  "stop sign",
  "tent",
  "tooth",
  "toothbrush",
  "traffic light",
  "triangle",
  "asparagus",
  "backpack",
  "beard",
  "bicycle",
  "boomerang",
  "bottlecap",
  "brain",
  "bridge",
  "broom",
  "camera",
  "cannon",
  "cloud",
  "clock",
  "cow",
  "crown",
  "elbow",
  "dumbbell",
  "flip flops",
  "grapes",
  "hourglass",
  "hot dog",
  "map",
  "microwave",
  "mouth",
  "mug",
  "paint can",
  "pants",
  "paper clip",
  "penguin",
  "potato",
  "power outlet",
  "purse",
  "rake",
  "rollerskates",
  "sandwich",
  "saw",
  "screwdriver",
  "scissors",
  "skull",
  "squirrel",
  "strawberry",
  "sword",
  "tornado",
  "train",
  "vase",
  "whale",
  "wheel",
  "zebra",
  "zigzag",
  "ambulance",
  "axe",
  "bathtub",
  "basket",
  "bed",
  "blueberry",
  "book",
  "bracelet",
  "bowtie",
  "broccoli",
  "ceiling fan",
  "computer",
  "couch",
  "feather",
  "fence",
  "firetruck",
  "flamingo",
  "guitar",
  "horse",
  "lion",
  "lighthouse",
  "matches",
  "monkey",
  "motorbike",
  "onion",
  "paintbrush",
  "passport",
  "pizza",
  "rhinoceros",
  "shark",
  "shovel",
  "snake",
  "speedboat",
  "spider",
  "stethoscope",
  "sweater",
  "swan",
  "toe",
  "toaster",
  "underwear",
  "barn",
  "belt",
  "bucket",
  "cake",
  "cell phone",
  "compass",
  "diving board",
  "dishwasher",
  "face",
  "duck",
  "finger",
  "golf club",
  "helmet",
  "hot tub",
  "knife",
  "lobster",
  "mailbox",
  "microphone",
  "moustache",
  "panda",
  "peas",
  "piano",
  "radio",
  "sleeping bag",
  "snorkel",
  "streetlight",
  "toothpaste",
  "violin",
  "watermelon",
  "windmill"
];

/** Accuracy top-1 đo được của MỌI class đã đo — vết để soi lại, không dùng lúc chạy. */
export const MEASURED_TOP1: Readonly<Record<string, number>> = {
  "apple": 0.9,
  "asparagus": 0.75,
  "ambulance": 0.7,
  "anvil": 0.85,
  "axe": 0.7,
  "arm": 0.8,
  "airplane": 0.95,
  "ant": 0.9,
  "alarm clock": 0.85,
  "aircraft carrier": 0.15,
  "angel": 0.9,
  "animal migration": 0.8,
  "backpack": 0.75,
  "banana": 1,
  "barn": 0.65,
  "baseball bat": 0.8,
  "bathtub": 0.7,
  "basket": 0.7,
  "baseball": 0.8,
  "basketball": 0.85,
  "bandage": 0.85,
  "beach": 0.55,
  "bear": 0.45,
  "beard": 0.75,
  "bat": 0.85,
  "bed": 0.7,
  "belt": 0.65,
  "bee": 0.9,
  "bird": 0.4,
  "bench": 0.4,
  "bicycle": 0.75,
  "blueberry": 0.7,
  "binoculars": 0.8,
  "book": 0.7,
  "blackberry": 0.55,
  "boomerang": 0.75,
  "birthday cake": 0.4,
  "bottlecap": 0.75,
  "bracelet": 0.7,
  "bowtie": 0.7,
  "brain": 0.75,
  "bread": 0.5,
  "bridge": 0.75,
  "broccoli": 0.7,
  "broom": 0.75,
  "bulldozer": 0.85,
  "bus": 0.55,
  "bucket": 0.65,
  "bush": 0.55,
  "butterfly": 1,
  "cake": 0.65,
  "cactus": 1,
  "calendar": 0.9,
  "cat": 0.8,
  "calculator": 0.8,
  "canoe": 0.5,
  "candle": 0.85,
  "camel": 0.85,
  "camera": 0.75,
  "camouflage": 0.55,
  "car": 0.85,
  "campfire": 0.85,
  "carrot": 0.9,
  "castle": 0.85,
  "ceiling fan": 0.7,
  "cannon": 0.75,
  "cell phone": 0.65,
  "circle": 0.9,
  "cello": 0.55,
  "chandelier": 0.85,
  "chair": 0.8,
  "cloud": 0.75,
  "clock": 0.75,
  "church": 0.9,
  "compass": 0.65,
  "coffee cup": 0.6,
  "computer": 0.7,
  "cookie": 0.85,
  "clarinet": 0.6,
  "cooler": 0.45,
  "couch": 0.7,
  "cow": 0.75,
  "crab": 0.85,
  "crayon": 0.5,
  "cruise ship": 0.85,
  "crocodile": 0.8,
  "crown": 0.75,
  "diamond": 0.8,
  "dolphin": 0.5,
  "diving board": 0.65,
  "dog": 0.5,
  "dishwasher": 0.65,
  "cup": 0.55,
  "donut": 0.85,
  "envelope": 0.95,
  "dragon": 0.6,
  "door": 0.85,
  "dresser": 0.8,
  "face": 0.65,
  "drill": 0.9,
  "drums": 0.8,
  "duck": 0.65,
  "ear": 0.85,
  "elephant": 0.8,
  "elbow": 0.75,
  "dumbbell": 0.75,
  "eye": 0.8,
  "eraser": 0.55,
  "fish": 0.85,
  "eyeglasses": 0.95,
  "fan": 0.6,
  "feather": 0.7,
  "fence": 0.7,
  "finger": 0.65,
  "fire hydrant": 0.8,
  "fireplace": 1,
  "firetruck": 0.7,
  "flip flops": 0.75,
  "flamingo": 0.7,
  "flashlight": 0.9,
  "flower": 0.95,
  "flying saucer": 0.85,
  "fork": 0.8,
  "floor lamp": 0.95,
  "foot": 0.6,
  "frog": 0.55,
  "frying pan": 0.85,
  "garden hose": 0.25,
  "garden": 0.9,
  "giraffe": 0.85,
  "grapes": 0.75,
  "goatee": 0.9,
  "golf club": 0.65,
  "grass": 0.85,
  "hamburger": 1,
  "hammer": 0.9,
  "harp": 0.85,
  "guitar": 0.7,
  "hat": 0.95,
  "hand": 0.9,
  "headphones": 0.85,
  "hedgehog": 0.85,
  "helicopter": 1,
  "hexagon": 0.55,
  "house": 0.8,
  "helmet": 0.65,
  "hockey stick": 0.55,
  "hockey puck": 0.6,
  "horse": 0.7,
  "hospital": 0.85,
  "hot air balloon": 0.8,
  "hourglass": 0.75,
  "hot dog": 0.75,
  "hot tub": 0.65,
  "house plant": 0.85,
  "hurricane": 0.6,
  "ice cream": 1,
  "jacket": 0.85,
  "jail": 0.95,
  "key": 0.85,
  "kangaroo": 0.9,
  "knee": 0.85,
  "keyboard": 0.6,
  "line": 0.85,
  "ladder": 1,
  "knife": 0.65,
  "lantern": 0.6,
  "laptop": 0.85,
  "leaf": 0.85,
  "leg": 0.4,
  "lighter": 0.85,
  "light bulb": 0.85,
  "lightning": 0.8,
  "lollipop": 0.9,
  "lipstick": 0.85,
  "lion": 0.7,
  "lobster": 0.65,
  "map": 0.75,
  "mailbox": 0.65,
  "lighthouse": 0.7,
  "marker": 0.5,
  "matches": 0.7,
  "megaphone": 0.8,
  "microphone": 0.65,
  "mermaid": 0.95,
  "monkey": 0.7,
  "microwave": 0.75,
  "mosquito": 0.5,
  "moon": 0.35,
  "motorbike": 0.7,
  "mouse": 0.5,
  "mountain": 0.85,
  "moustache": 0.65,
  "mouth": 0.75,
  "mug": 0.75,
  "mushroom": 0.85,
  "nail": 0.55,
  "necklace": 0.85,
  "nose": 0.9,
  "octagon": 0.85,
  "octopus": 0.9,
  "ocean": 0.8,
  "onion": 0.7,
  "oven": 0.35,
  "owl": 0.8,
  "paint can": 0.75,
  "paintbrush": 0.7,
  "palm tree": 0.9,
  "panda": 0.65,
  "pants": 0.75,
  "paper clip": 0.75,
  "parachute": 0.85,
  "parrot": 0.6,
  "passport": 0.7,
  "pear": 0.8,
  "peanut": 0.8,
  "peas": 0.65,
  "pickup truck": 0.45,
  "pencil": 0.5,
  "piano": 0.65,
  "picture frame": 0.95,
  "penguin": 0.75,
  "pig": 0.8,
  "pillow": 0.6,
  "pineapple": 0.8,
  "pizza": 0.7,
  "pliers": 0.5,
  "pool": 0.45,
  "police car": 0.4,
  "pond": 0.55,
  "popsicle": 0.9,
  "potato": 0.75,
  "power outlet": 0.75,
  "postcard": 0.5,
  "purse": 0.75,
  "rabbit": 0.85,
  "raccoon": 0.4,
  "radio": 0.65,
  "rain": 0.9,
  "rainbow": 0.9,
  "rifle": 0.8,
  "rake": 0.75,
  "rhinoceros": 0.7,
  "river": 0.35,
  "remote control": 0.8,
  "roller coaster": 0.8,
  "rollerskates": 0.75,
  "sailboat": 0.9,
  "sandwich": 0.75,
  "saw": 0.75,
  "saxophone": 0.85,
  "school bus": 0.35,
  "scorpion": 0.9,
  "screwdriver": 0.75,
  "scissors": 0.75,
  "see saw": 0.85,
  "sea turtle": 0.9,
  "shark": 0.7,
  "sheep": 0.95,
  "shoe": 0.9,
  "shovel": 0.7,
  "shorts": 0.9,
  "sink": 1,
  "skateboard": 0.8,
  "skull": 0.75,
  "skyscraper": 0.8,
  "sleeping bag": 0.65,
  "snail": 1,
  "smiley face": 0.8,
  "snake": 0.7,
  "snorkel": 0.65,
  "snowflake": 0.9,
  "snowman": 0.9,
  "speedboat": 0.7,
  "soccer ball": 0.85,
  "sock": 0.85,
  "spider": 0.7,
  "spoon": 0.95,
  "spreadsheet": 0.45,
  "star": 1,
  "square": 0.9,
  "stairs": 0.85,
  "squirrel": 0.75,
  "squiggle": 0.45,
  "steak": 0.5,
  "stereo": 0.5,
  "stethoscope": 0.7,
  "stitches": 0.8,
  "stove": 0.8,
  "strawberry": 0.75,
  "stop sign": 0.8,
  "string bean": 0.4,
  "streetlight": 0.65,
  "sun": 0.85,
  "submarine": 0.85,
  "suitcase": 0.6,
  "sweater": 0.7,
  "swan": 0.7,
  "swing set": 0.95,
  "sword": 0.75,
  "t-shirt": 1,
  "table": 0.85,
  "syringe": 0.9,
  "teapot": 0.85,
  "teddy-bear": 0.85,
  "telephone": 0.6,
  "television": 0.9,
  "tennis racquet": 0.95,
  "tent": 0.8,
  "The Eiffel Tower": 0.95,
  "The Great Wall of China": 0.45,
  "The Mona Lisa": 0.95,
  "toe": 0.7,
  "tiger": 0.45,
  "toaster": 0.7,
  "tooth": 0.8,
  "toothbrush": 0.8,
  "toilet": 0.85,
  "toothpaste": 0.65,
  "tornado": 0.75,
  "tractor": 0.85,
  "traffic light": 0.8,
  "train": 0.75,
  "triangle": 0.8,
  "tree": 0.85,
  "trombone": 0.55,
  "truck": 0.35,
  "trumpet": 0.6,
  "umbrella": 0.95,
  "underwear": 0.7,
  "washing machine": 1,
  "van": 0.5,
  "vase": 0.75,
  "violin": 0.65,
  "watermelon": 0.65,
  "waterslide": 0.85,
  "whale": 0.75,
  "wheel": 0.75,
  "wine bottle": 0.9,
  "windmill": 0.65,
  "wine glass": 0.95,
  "yoga": 0.6,
  "wristwatch": 0.9,
  "zebra": 0.75,
  "zigzag": 0.75
};
